version: '3.3'

services:
  mlflow:
    build: ./mlflow
    image: "mlflow"
    ports:
      - "5050:5050"
    volumes:
      - ./mlruns:/mlflow/mlruns
  app:
    build: ./app
    image: "experiment"
    depends_on:
      - mlflow
    links:
      - "mlflow:5050"
    volumes:
      - ./mlruns:/app/mlruns
      - ./app:/app
    environment:
      MLFLOW_TRACKING_URI: 'http://mlflow:5050'
    restart:
      on-failure
